In [2]:
# import the package
import numpy as np

In [3]:
# craete a numpy 2d Array
L = [[23,45],[67,89],[56,78]]
a2 = np.array(L)

In [12]:
# ndim - no of dimensions
print(a2.ndim)
# shape - shape as a tuple
print(a2.shape)
# size - No of elements
print(a2.size)
# itemsize - returns no of bytes required to store an element
print(a2.itemsize) 
# dtype - Data type of the numpy array
print(a2.dtype)
# Total size of the array in bytes
print(a2.size*a2.itemsize)
# Total size of the array in bytes
print(a2.nbytes)

2
(3, 2)
6
4
int32
24
24


In [10]:
# Iteration through numpy 2d array
for i in a2:
    print(i)
    print(type(i))
    break
    

[23 45]
<class 'numpy.ndarray'>


In [9]:
# Iteration through list of lists
for i in L:
    print(i)
    print(type(i))
    break

[23, 45]
<class 'list'>


Initializing Arrays
- np.zeros
- np.ones
- np.eye
- np.full
- np.diag

In [11]:
# Creating an array with all ones
print(np.ones((2,3))) 

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
np.ones(2)

array([1., 1.])

In [14]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

To check the documentation of a function use ***help***

In [19]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

In [20]:
np.ones((3,4),dtype=np.int8)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [24]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [25]:
np.zeros((2,2),dtype=bool)

array([[False, False],
       [False, False]])

**np.eye()**<br>
To create an array with diagonal elements as 1 and remaining elemnts as zero 

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

**np.full()**<br>
To create an array with fill value

In [29]:
np.full((3,2),9)

array([[9, 9],
       [9, 9],
       [9, 9]])

In [30]:
np.full((3,2),9.7)

array([[9.7, 9.7],
       [9.7, 9.7],
       [9.7, 9.7]])

**np.diag()**<br>
Create an ndarray with given diagonal elements

In [33]:
np.diag([7,9,23])

array([[ 7,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 23]])

In [34]:
np.diag([1,1,1])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

To craete a numpy array with in a range of values<br>
- np.arange
- np.linspace 

In [37]:
print(np.arange(10))
print(np.arange(2,10))
print(np.arange(2,10,2))
print(np.arange(2,5,0.5))

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 4 6 8]
[2.  2.5 3.  3.5 4.  4.5]


In [40]:
print(np.linspace(5,10,2))
print(np.linspace(5,10,3))
print(np.linspace(5,10,4))

[ 5. 10.]
[ 5.   7.5 10. ]
[ 5.          6.66666667  8.33333333 10.        ]


Difference between the functions:<br>
- np.arange
    - stop value is exclusive
    - returns evenly spcaced values, space is equal to step size
    - number of values in returned array are based on start,stop and step values
- np.linspace
    - by default stop value is inclusive
    - returns given number of evenly spaced values calculated over start and stop value  

Basic Math Operators on Numpy arrays

In [24]:
a = np.array([1,2,3])
b = np.array([1,1,1])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)
print(a**b)

[2 3 4]
[0 1 2]
[1 2 3]
[1. 2. 3.]
[1 2 3]
[0 0 0]
[1 2 3]


**Broadcasting**<br>
How to Handle operators on two numpy arrays with different shapes.<br>  
**General Broadcasting Rules**<br>
When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward. Two dimensions are compatible when<br>

    - they are equal, or
    - one of them is 1<br>
    
If these conditions are not met, a ValueError: operands could not be broadcast together exception is thrown, indicating that the arrays have incompatible shapes. The size of the resulting array is the maximum size along each dimension of the input arrays.

In [25]:
# Adding a scalar to a numpy array
a+1

array([2, 3, 4])

In [43]:
# Adding an array with one value to a numpy array
a+[1]

array([2, 3, 4])

In [27]:
a + np.array([1,1])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [29]:
# Broadcasting with different shapes
b1 = np.full((3,4,2),2)
b2 = 1
b3 = np.array([2,3])
b4 = np.array([[1],[2]])
print(b1)
print(b2)
print(b3)
print(b4)

[[[2 2]
  [2 2]
  [2 2]
  [2 2]]

 [[2 2]
  [2 2]
  [2 2]
  [2 2]]

 [[2 2]
  [2 2]
  [2 2]
  [2 2]]]
1
[2 3]
[[1]
 [2]]


In [30]:
print(b3.shape,b4.shape)
b3 + b4

(2,) (2, 1)


array([[3, 4],
       [4, 5]])

In [48]:
b3

array([2, 3])

In [49]:
b4

array([[1],
       [2]])

In [50]:
b4 +b3

array([[3, 4],
       [4, 5]])

In [51]:
b1 = np.full((3,4,2),2)
b5 = np.full((1,3,1,2),4) #  1,3,4,2

In [53]:
(b1+b5).shape

(1, 3, 4, 2)

In [31]:
# Array Slicing 
a = np.arange(25)
print(a[:2])
print(a[5:10])
print(a[2:24:5])
print(a[1])
print(a[-1])
print(a[[2,5,9]]) # Pass a list indices
print(a[[24,2,1,6]])

[0 1]
[5 6 7 8 9]
[ 2  7 12 17 22]
1
24
[2 5 9]
[24  2  1  6]


**Random Subpackage**<br>
- randint()
- random()
- normal()
- randn()

In [74]:
np.random.randint(7,10,(2,2)) # The third parmaeter is the shape of output array

array([[9, 8],
       [9, 9]])

In [73]:
np.random.randint(1,10,(2,2))

array([[1, 5],
       [8, 2]])

In [82]:
np.random.random((4,5))

array([[0.20529264, 0.75000959, 0.49346759, 0.99099902, 0.32146762],
       [0.86059252, 0.74198301, 0.39881956, 0.95576335, 0.96493721],
       [0.02647369, 0.18198029, 0.35656001, 0.78440242, 0.93145487],
       [0.40839584, 0.22164765, 0.45023366, 0.58639713, 0.12057984]])

In [88]:
np.random.normal() # Generate values on normal distribution curve

0.5035322251542212

In [89]:
np.random.randn()

-0.5445024007566264

In [91]:
np.random.randn(2,3)

array([[1.91435266, 0.69268998, 0.91380409],
       [0.12585219, 0.97175674, 0.02384942]])

In [94]:
np.random.normal(size=(2,3))

array([[ 0.55152259, -0.23236507, -0.09768494],
       [ 0.05842657, -1.8390685 , -1.20502543]])

List of functions and classes available in random subpackage in numpy

In [95]:
dir(np.random)

['Lock',
 'RandomState',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'absolute_import',
 'beta',
 'binomial',
 'bytes',
 'chisquare',
 'choice',
 'dirichlet',
 'division',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'np',
 'operator',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'print_function',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponential',
 'standard_gamma',
 'standard_normal',
 'standard_t',
 'test',
 'triangular',
 'uniform',
 'vonmises',
 'wald',
 'warnings',
 'weibull',
 'zipf']

**Statistical Functions**
- min()
- max()
- sum()
- mean()
- median()
- quantile()

In [36]:
a1 = np.array([10,20,30,40,50])
np.min(a1)
np.max(a1)
np.sum(a1)
np.mean(a1)
np.median(a1)

30.0

In [103]:
print(np.quantile(a1,0.25))

20.0


In [32]:
a2 = np.random.randint(12,20,(2,2))
print(a2)
print(np.sum(a2))

[[14 13]
 [14 17]]
58


In [33]:
np.sum(a2,axis=1)

array([27, 31])

In [34]:
np.sum(a2,axis=1,keepdims=True)

array([[27],
       [31]])

In [35]:
np.sum(a2,axis=0)

array([28, 30])

In [109]:
np.sum(a2,axis=0,keepdims=True)

array([[24, 35]])

In [110]:
np.std(a2)

2.947456530637899