**Topics covered in last session**
- arange,Linspace
- random
    - randint
    - randn 
    - normal    
- Basic Operatords +,-,%,/,//,**
- Initializing arrays
    - zeros
    - ones
    - full
    - eye
    - diag
- statistics
    - min
    - max
    - median
    - quantile
    - mean
    - sum

In [1]:
import numpy as np
a = np.arange(7)
b = np.full((7),1)
print(a)
print(b)

[0 1 2 3 4 5 6]
[1 1 1 1 1 1 1]


In [5]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.mod(a,b))

[1 2 3 4 5 6 7]
[-1  0  1  2  3  4  5]
[0 1 2 3 4 5 6]
[0. 1. 2. 3. 4. 5. 6.]
[0 0 0 0 0 0 0]


In [7]:
# Create a 3d Array
np.random.seed(23)
a3 = np.random.randint(100,size=(3,5,4))
a3

array([[[83, 40, 73, 54],
        [31, 76, 91, 39],
        [90, 25, 51,  6],
        [45, 12, 49, 66],
        [75, 85, 69, 64]],

       [[12, 21, 48, 41],
        [79, 90, 62, 57],
        [19, 33, 59, 39],
        [15, 36, 65,  1],
        [43, 15, 86, 83]],

       [[58, 25, 66, 74],
        [35, 96, 56, 13],
        [60, 22, 38, 31],
        [94, 78,  0, 21],
        [ 6, 32, 98, 32]]])

In [8]:
# Iteration over a 3d Array
for i in a3:
    print(i)
    break

[[83 40 73 54]
 [31 76 91 39]
 [90 25 51  6]
 [45 12 49 66]
 [75 85 69 64]]


Slicing or Subsetting

In [9]:
a3[:] # All the elemnts 

array([[[83, 40, 73, 54],
        [31, 76, 91, 39],
        [90, 25, 51,  6],
        [45, 12, 49, 66],
        [75, 85, 69, 64]],

       [[12, 21, 48, 41],
        [79, 90, 62, 57],
        [19, 33, 59, 39],
        [15, 36, 65,  1],
        [43, 15, 86, 83]],

       [[58, 25, 66, 74],
        [35, 96, 56, 13],
        [60, 22, 38, 31],
        [94, 78,  0, 21],
        [ 6, 32, 98, 32]]])

In [15]:
a3[1] # 2nd 5*3 Array shape(5,4)

array([[12, 21, 48, 41],
       [79, 90, 62, 57],
       [19, 33, 59, 39],
       [15, 36, 65,  1],
       [43, 15, 86, 83]])

In [16]:
a3[:1] # a3[0] a 5*3 array shape(5,4)

array([[[83, 40, 73, 54],
        [31, 76, 91, 39],
        [90, 25, 51,  6],
        [45, 12, 49, 66],
        [75, 85, 69, 64]]])

In [19]:
#a3[0] and a3[1] shape(2,5,4) 
print(a3[:2].shape)
a3[:2] 

(2, 5, 4)


array([[[83, 40, 73, 54],
        [31, 76, 91, 39],
        [90, 25, 51,  6],
        [45, 12, 49, 66],
        [75, 85, 69, 64]],

       [[12, 21, 48, 41],
        [79, 90, 62, 57],
        [19, 33, 59, 39],
        [15, 36, 65,  1],
        [43, 15, 86, 83]]])

In [10]:
print(a3[0][2][2]) # To access elemnt 51 in the First 5*4 array
print(a3[0,2,2])

51
51


In [11]:
a3[1,:,2] #[slicing in dim1: slicing in dim2:slicing in dim3]

array([48, 62, 59, 65, 86])

In [25]:
a3[:2,1:3,2] # [slicing in dim1: slicing in dim2:selecting a specific index]

array([[91, 51],
       [62, 59]])

In [26]:
a3[[2,1,0]] # [list of indices in dim1]

array([[[58, 25, 66, 74],
        [35, 96, 56, 13],
        [60, 22, 38, 31],
        [94, 78,  0, 21],
        [ 6, 32, 98, 32]],

       [[12, 21, 48, 41],
        [79, 90, 62, 57],
        [19, 33, 59, 39],
        [15, 36, 65,  1],
        [43, 15, 86, 83]],

       [[83, 40, 73, 54],
        [31, 76, 91, 39],
        [90, 25, 51,  6],
        [45, 12, 49, 66],
        [75, 85, 69, 64]]])

In [27]:
a3[:,[3,1]] # [slicing in dim1:list of indices in dim2]

array([[[45, 12, 49, 66],
        [31, 76, 91, 39]],

       [[15, 36, 65,  1],
        [79, 90, 62, 57]],

       [[94, 78,  0, 21],
        [35, 96, 56, 13]]])

In [28]:
#[list of indices in dim1: list of indices in dim2:list od indices in dim3]
# Index selection using Braodcating
print(a3[[2,1],[1,3],[3,2]])  # [2,1,3] [1,3,2]
print(a3[2,1,3],a3[1,3,2]) 

array([13, 65])

In [12]:
# To generate same values 
np.random.seed(0)
a2 = np.random.randint(100,size=(5,7))
a2

array([[44, 47, 64, 67, 67,  9, 83],
       [21, 36, 87, 70, 88, 88, 12],
       [58, 65, 39, 87, 46, 88, 81],
       [37, 25, 77, 72,  9, 20, 80],
       [69, 79, 47, 64, 82, 99, 88]])

In [41]:
a2 = np.arange(35).reshape(5,7)
a2

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [13]:
# Select alternate columns
# Select alternate rows
#a2[:,[1,3,5]]
#a2[:,[0,2,4,6]]
#a2[:,0::2]
a2[:,1::2]

array([[47, 67,  9],
       [36, 70, 88],
       [65, 87, 88],
       [25, 72, 20],
       [79, 64, 99]])

In [50]:
a2[0::2,:]
a2[[0,2,4],:]
a2[1::2,:]
a2[[1,3],:]

array([[ 7,  8,  9, 10, 11, 12, 13],
       [21, 22, 23, 24, 25, 26, 27]])

In [56]:
# Check the output
a2[[1,2,0],[2,4,6]] #[(1,2),(2,4),(0,6)]

array([ 9, 18,  6])

In [57]:
a2[::2,::2]

array([[ 0,  2,  4,  6],
       [14, 16, 18, 20],
       [28, 30, 32, 34]])

Boolean or Fancy Indexing

In [58]:
a2 >10

array([[False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [61]:
np.sum(a2>10) # Caluculating the number of values greater than 10

24

In [14]:
# + opeartor with boolean data
print(True +  True)
print(True + False)

2
1


In [15]:
# Selction using Boolean Index
a2[a2>10]

array([44, 47, 64, 67, 67, 83, 21, 36, 87, 70, 88, 88, 12, 58, 65, 39, 87,
       46, 88, 81, 37, 25, 77, 72, 20, 80, 69, 79, 47, 64, 82, 99, 88])

In [17]:
# To get even numbers from an array
a5 = np.array([67,89,23,44,32,78,99])
a5 %2 ==0

array([False, False, False,  True,  True,  True, False])

In [18]:
a5[a5 %2==0]

array([44, 32, 78])

In [19]:
# Assigning a value to selected elemnts
a5[a5 %2==0] = 0
a5

array([67, 89, 23,  0,  0,  0, 99])

In [20]:
# Reaplacing negative numbers with absolute value
a6 = np.array([92,-127,89,-34,2,67])
# [92,127,89,34,2,67]
#a6[a6<0]=[127,34]
# a6[a6<0] = np.mean(a6)

In [21]:
np.abs(a6)

array([ 92, 127,  89,  34,   2,  67])

In [22]:
np.mean(a6)

14.833333333333334

Array manipulation
    - reshape
    - flatten
    - resize
    

In [23]:
# no of elemnts in the new array and old array sholud be same
a7 = np.arange(45).reshape((9,5))
a7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [78]:
# Different possible shapes to convert it into 3d array
a7.reshape(1,9,5)
a7.reshape(3,3,5)
a7.reshape(5,3,3)
a7.resahpe(3,5,3)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

In [24]:
# may use unknown value -1 in any one of the dimension
# It will calculate the possible no of elemnts in the unknown dimension
a3.reshape(5,3,-1)

array([[[83, 40, 73, 54],
        [31, 76, 91, 39],
        [90, 25, 51,  6]],

       [[45, 12, 49, 66],
        [75, 85, 69, 64],
        [12, 21, 48, 41]],

       [[79, 90, 62, 57],
        [19, 33, 59, 39],
        [15, 36, 65,  1]],

       [[43, 15, 86, 83],
        [58, 25, 66, 74],
        [35, 96, 56, 13]],

       [[60, 22, 38, 31],
        [94, 78,  0, 21],
        [ 6, 32, 98, 32]]])

In [25]:
# Should use only one unknown dimension
a3.reshape(-1,-1,-1) 

ValueError: can only specify one unknown dimension

In [26]:
a7.reshape(5,4,-1) #Error

ValueError: cannot reshape array of size 45 into shape (5,4,newaxis)

In [27]:
# It will modify the original array
a7.resize(5,9)

In [28]:
a7

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44]])

In [29]:
# It will not modify the original array
np.resize(a7,(5,10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44,  0,  1,  2,  3,  4]])

Check the documenattion for
- np.resize()
- np.ndarray.resize

In [30]:
help(np.ndarray.resize)

Help on method_descriptor:

resize(...)
    a.resize(new_shape, refcheck=True)
    
    Change shape and size of array in-place.
    
    Parameters
    ----------
    new_shape : tuple of ints, or `n` ints
        Shape of resized array.
    refcheck : bool, optional
        If False, reference count will not be checked. Default is True.
    
    Returns
    -------
    None
    
    Raises
    ------
    ValueError
        If `a` does not own its own data or references or views to it exist,
        and the data memory must be changed.
        PyPy only: will always raise if the data memory must be changed, since
        there is no reliable way to determine if references or views to it
        exist.
    
    SystemError
        If the `order` keyword argument is specified. This behaviour is a
        bug in NumPy.
    
    See Also
    --------
    resize : Return a new array with the specified shape.
    
    Notes
    -----
    This reallocates space for the data area if necessary

In [87]:
help(a7.resize)

Help on built-in function resize:

resize(...) method of numpy.ndarray instance
    a.resize(new_shape, refcheck=True)
    
    Change shape and size of array in-place.
    
    Parameters
    ----------
    new_shape : tuple of ints, or `n` ints
        Shape of resized array.
    refcheck : bool, optional
        If False, reference count will not be checked. Default is True.
    
    Returns
    -------
    None
    
    Raises
    ------
    ValueError
        If `a` does not own its own data or references or views to it exist,
        and the data memory must be changed.
        PyPy only: will always raise if the data memory must be changed, since
        there is no reliable way to determine if references or views to it
        exist.
    
    SystemError
        If the `order` keyword argument is specified. This behaviour is a
        bug in NumPy.
    
    See Also
    --------
    resize : Return a new array with the specified shape.
    
    Notes
    -----
    This realloca

In [31]:
# To convert an array into 1d
a7.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [93]:
# Creating 2d array with one row
a7.reshape(1,5*9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44]])

In [32]:
#Flatten using reshape
a7.reshape(5*9)
a7.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [96]:
# Creating 2d array with one column
a7.reshape(5*9,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44]])

In [97]:
np.reshape(a7,(5*9))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

**np.swapaxes()**<br>
Interchanging two axes in an array

In [105]:
np.swapaxes(a7,0,1).shape

(9, 5)

In [100]:
a7.shape

(5, 9)

In [102]:
a3.shape

(3, 5, 4)

In [104]:
np.swapaxes(a3,0,1).shape

(5, 3, 4)

Logor Functions

In [106]:
import math
math.log(2)

0.6931471805599453

In [107]:
np.log(2)

0.6931471805599453

In [108]:
np.log([2,4,6])

array([0.69314718, 1.38629436, 1.79175947])

In [111]:
np.log2(2)

1.0

In [112]:
np.log1p(1) # np.log1p(x)=np.log(1+x)

0.6931471805599453

In [113]:
np.log1p(0)

0.0

Exponential

In [114]:
print(np.exp(1))
print(np.log(np.exp(1)))

2.718281828459045

In [119]:
np.exp2(2)

4.0

In [120]:
np.expm1(2) #np.exp(x) - 1

6.38905609893065

In [124]:
np.exp(2) -1

6.38905609893065