#### Mathematical Operators

In [1]:
import numpy as np
help(np.diag)

Help on function diag in module numpy:

diag(v, k=0)
    Extract a diagonal or construct a diagonal array.
    
    See the more detailed documentation for ``numpy.diagonal`` if you use this
    function to extract a diagonal and wish to write to the resulting array;
    whether it returns a copy or a view depends on what version of numpy you
    are using.
    
    Parameters
    ----------
    v : array_like
        If `v` is a 2-D array, return a copy of its `k`-th diagonal.
        If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
        diagonal.
    k : int, optional
        Diagonal in question. The default is 0. Use `k>0` for diagonals
        above the main diagonal, and `k<0` for diagonals below the main
        diagonal.
    
    Returns
    -------
    out : ndarray
        The extracted diagonal or constructed diagonal array.
    
    See Also
    --------
    diagonal : Return specified diagonals.
    diagflat : Create a 2-D array with the flattened input 

In [2]:
np.diag([2,3,4])

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [3]:
a = np.arange(5)
b = np.ones(5)
print(a)
print(b)

[0 1 2 3 4]
[1. 1. 1. 1. 1.]


In [4]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a//b)

[1. 2. 3. 4. 5.]
[-1.  0.  1.  2.  3.]
[0. 1. 2. 3. 4.]
[0. 1. 2. 3. 4.]
[0. 0. 0. 0. 0.]
[0. 1. 2. 3. 4.]


In [5]:
print(a*2)
print(a**2)
print(a+2)
print(a-2)
print(a/2)

[0 2 4 6 8]
[ 0  1  4  9 16]
[2 3 4 5 6]
[-2 -1  0  1  2]
[0.  0.5 1.  1.5 2. ]


#### random

In [10]:
np.random.randint(100)

14

In [13]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of mtrand.RandomState instance
    randint(low, high=None, size=None, dtype='l')
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    Parameters
    ----------
    low : int
        Lowest (signed) integer to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above for behavior if ``high=None``).
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, i

In [14]:
np.random.randint(100,size=2)

array([46, 10])

In [15]:
np.random.randint(100,size=5)

array([33,  0, 40, 55, 17])

In [17]:
np.random.randint(100,size=(5,2))

array([[53, 76],
       [90, 24],
       [41, 41],
       [86, 90],
       [14, 18]])

In [18]:
np.random.randint(50,100,size=(5,2))

array([[85, 80],
       [87, 79],
       [97, 73],
       [76, 72],
       [50, 77]])

In [19]:
np.random.random()

0.7331561035307335

In [20]:
help(np.random.random)

Help on built-in function random_sample:

random_sample(...) method of mtrand.RandomState instance
    random_sample(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0).
    
    Results are from the "continuous uniform" distribution over the
    stated interval.  To sample :math:`Unif[a, b), b > a` multiply
    the output of `random_sample` by `(b-a)` and add `a`::
    
      (b - a) * random_sample() + a
    
    Parameters
    ----------
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    
    Returns
    -------
    out : float or ndarray of floats
        Array of random floats of shape `size` (unless ``size=None``, in which
        case a single float is returned).
    
    Examples
    --------
    >>> np.random.random_sample()
    0.47108547995356098
    >>> type(np.random.random_

In [21]:
np.random.random(10)

array([0.69679204, 0.1201844 , 0.73308847, 0.8574058 , 0.67955468,
       0.29353911, 0.2892792 , 0.42813324, 0.70717154, 0.39100029])

In [22]:
np.random.random((2,3))

array([[0.08307603, 0.38885422, 0.13037537],
       [0.92108118, 0.80952178, 0.34493674]])

In [23]:
np.random.rand()

0.48800505951294104

In [24]:
help(np.random.rand)

Help on built-in function rand:

rand(...) method of mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, should all be positive.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Notes
    -----
    This is a convenience function. If you want an interface that
    takes a shape-tuple as the first argument, refer to
    np.random.random_sample .
    
    Examples
    --------
    >>> np.random.rand(3,2)
    array([[ 0.14022471,  0.96360618],  #random
           [ 0.37601032,  0.25528411],  #random
           [ 0.49313049,  0.94909878]]

In [25]:
np.random.rand(5)

array([0.69174351, 0.07705789, 0.19678009, 0.37746089, 0.57672622])

In [26]:
np.random.rand(2,5)

array([[0.83236148, 0.34888686, 0.49275037, 0.15383755, 0.87065375],
       [0.56510078, 0.08317345, 0.00280924, 0.96270358, 0.17581354]])

In [27]:
np.random.random(2,5)

TypeError: random_sample() takes at most 1 positional argument (2 given)

In [28]:
dir(np.random)

['Lock',
 'RandomState',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'absolute_import',
 'beta',
 'binomial',
 'bytes',
 'chisquare',
 'choice',
 'dirichlet',
 'division',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'np',
 'operator',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'print_function',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponential',
 'standard_gamma',
 'standard_normal',
 'standard_t',
 'test',
 'triangular',
 'uniform',
 'vonmises',
 'wald',
 'warnings',
 'weibull',
 'zipf']

In [29]:
help(np.random.shuffle)

Help on built-in function shuffle:

shuffle(...) method of mtrand.RandomState instance
    shuffle(x)
    
    Modify a sequence in-place by shuffling its contents.
    
    This function only shuffles the array along the first axis of a
    multi-dimensional array. The order of sub-arrays is changed but
    their contents remains the same.
    
    Parameters
    ----------
    x : array_like
        The array or list to be shuffled.
    
    Returns
    -------
    None
    
    Examples
    --------
    >>> arr = np.arange(10)
    >>> np.random.shuffle(arr)
    >>> arr
    [1 7 5 2 9 4 3 6 0 8]
    
    Multi-dimensional arrays are only shuffled along the first axis:
    
    >>> arr = np.arange(9).reshape((3, 3))
    >>> np.random.shuffle(arr)
    >>> arr
    array([[3, 4, 5],
           [6, 7, 8],
           [0, 1, 2]])



In [31]:
r = np.arange(10,20)
np.random.shuffle(r)
print(r)

[10 12 16 15 11 13 17 19 18 14]


#### Array Manipulation
- np.array.reshape
- np.resize
- np.array.resize
- np.expand_dims
- np.array.flatten

In [33]:
a = np.arange(20)
a.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [35]:
a.reshape(13,2)

ValueError: cannot reshape array of size 20 into shape (13,2)

In [36]:
a.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [37]:
a.reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [38]:
a.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [39]:
a.reshape(20,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [40]:
a.reshape(1,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [41]:
help(np.resize)

Help on function resize in module numpy:

resize(a, new_shape)
    Return a new array with the specified shape.
    
    If the new array is larger than the original array, then the new
    array is filled with repeated copies of `a`.  Note that this behavior
    is different from a.resize(new_shape) which fills with zeros instead
    of repeated copies of `a`.
    
    Parameters
    ----------
    a : array_like
        Array to be resized.
    
    new_shape : int or tuple of int
        Shape of resized array.
    
    Returns
    -------
    reshaped_array : ndarray
        The new array is formed from the data in the old array, repeated
        if necessary to fill out the required number of elements.  The
        data are repeated in the order that they are stored in memory.
    
    See Also
    --------
    ndarray.resize : resize an array in-place.
    
    Notes
    -----
    i.e. it does not apply interpolation/extrapolation.
    It fills the return array with the required 

In [42]:
np.resize(a,(13,2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [ 0,  1],
       [ 2,  3],
       [ 4,  5]])

In [52]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [49]:
z= np.arange(20)
z.resize((13,2))

In [50]:
help(z.resize)

Help on built-in function resize:

resize(...) method of numpy.ndarray instance
    a.resize(new_shape, refcheck=True)
    
    Change shape and size of array in-place.
    
    Parameters
    ----------
    new_shape : tuple of ints, or `n` ints
        Shape of resized array.
    refcheck : bool, optional
        If False, reference count will not be checked. Default is True.
    
    Returns
    -------
    None
    
    Raises
    ------
    ValueError
        If `a` does not own its own data or references or views to it exist,
        and the data memory must be changed.
        PyPy only: will always raise if the data memory must be changed, since
        there is no reliable way to determine if references or views to it
        exist.
    
    SystemError
        If the `order` keyword argument is specified. This behaviour is a
        bug in NumPy.
    
    See Also
    --------
    resize : Return a new array with the specified shape.
    
    Notes
    -----
    This realloca

In [51]:
z

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [ 0,  0],
       [ 0,  0],
       [ 0,  0]])

In [54]:
np.expand_dims(a,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [55]:
np.expand_dims(a,0)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [56]:
a2 = np.arange(10).reshape(2,5)
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [57]:
np.expand_dims(a2,1)

array([[[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

In [59]:
np.expand_dims(a2,1).shape

(2, 1, 5)

In [58]:
np.expand_dims(a2,0)

array([[[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]])

In [62]:
help(np.expand_dims)

Help on function expand_dims in module numpy:

expand_dims(a, axis)
    Expand the shape of an array.
    
    Insert a new axis that will appear at the `axis` position in the expanded
    array shape.
    
    .. note:: Previous to NumPy 1.13.0, neither ``axis < -a.ndim - 1`` nor
       ``axis > a.ndim`` raised errors or put the new axis where documented.
       Those axis values are now deprecated and will raise an AxisError in the
       future.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axis : int
        Position in the expanded axes where the new axis is placed.
    
    Returns
    -------
    res : ndarray
        Output array. The number of dimensions is one greater than that of
        the input array.
    
    See Also
    --------
    squeeze : The inverse operation, removing singleton dimensions
    reshape : Insert, remove, and combine dimensions, and resize existing ones
    doc.indexing, atleast_1d, atleast_2d, atleast_3d
    
    Exa

In [60]:
a2.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
np.expand_dims(a2,0).flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Iteration over 1d,2d and 3d Arrays

In [66]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [63]:
for i in a:
    print(i)
    break

0


In [67]:
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [64]:
for i in a2:
    print(i)
    break

[0 1 2 3 4]


In [68]:
np.arange(12).reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [65]:
for i in np.arange(12).reshape(2,2,3):
    print(i)
    break

[[0 1 2]
 [3 4 5]]


Indexing,Slicing,Subset

In [69]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [71]:
print(a[0])
print(a[-1])

0
19


In [73]:
print(a[2:10])
print(a[2:12:3])

[2 3 4 5 6 7 8 9]
[ 2  5  8 11]


In [74]:
print(a[[1,10,3]])

[ 1 10  3]


Fancy Indexing

In [75]:
a %2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [76]:
a[a %2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [77]:
a[[True,False]]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 20 but corresponding boolean dimension is 2

In [78]:
a2 = np.arange(20).reshape(5,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [79]:
a2[0]

array([0, 1, 2, 3])

In [80]:
a2[-1]

array([16, 17, 18, 19])

In [81]:
a2[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
a2[[4,3,2,1,0]]

array([[16, 17, 18, 19],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [84]:
a2[[True,False,False,True,True]]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

rows - 0,1,2,3,4<br>
columns - 0,1,2,3<br>

In [87]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [93]:
a2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [89]:
print(a2[2,2])
print(a2[2][2])

10
10


In [90]:
a2[3,3]

15

In [92]:
a2[1:4]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [91]:
a2[1:4,2:4]

array([[ 6,  7],
       [10, 11],
       [14, 15]])

In [94]:
a2[[1,3,2],[3,2,1]] #[(1,3),(3,2),(2,1)]

array([ 7, 14,  9])