In [2]:
import numpy

In [3]:
numpy.array([1,2,3])

array([1, 2, 3])

In [4]:
import numpy as np
np.__version__

'1.16.2'

In [5]:
from numpy import array
array([1,2,3])

array([1, 2, 3])

In [6]:
from numpy import * 
# all the modules and subpackages will be imported

Numpy array creation from
- list
- tuple
- range

In [7]:
np.array([23,45,67])

array([23, 45, 67])

In [8]:
np.array((1,2,3))

array([1, 2, 3])

In [9]:
np.array(range(5,10))

array([5, 6, 7, 8, 9])

In [10]:
a = np.array(range(5,10))
print(a)
print(type(a))

[5 6 7 8 9]
<class 'numpy.ndarray'>


In [11]:
print(a.shape) # tuple
print(a.dtype) # data type
print(a.size) # no of elements
print(a.itemsize) # no of bytes for each items
print(a.ndim) # no of dimensions
print(a.nbytes)# total array size in bytes a.size * a.itemsize

(5,)
int32
5
4
1
20


In [12]:
l = [1]
t = (1,)
print(type(l),type(t))

<class 'list'> <class 'tuple'>


In [13]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
print(a2.shape) # tuple
print(a2.dtype) # data type
print(a2.size) # no of elements
print(a2.itemsize) # no of bytes for each items
print(a2.ndim) # no of dimensions
print(a2.nbytes)# total array size in bytes a.size * a.itemsize

(3, 3)
int32
9
4
2
36


In [15]:
print(a2.shape[1]) 

3


In [16]:
a = np.array([1,2,3,7],dtype=np.int8)
print(a.shape) # tuple
print(a.dtype) # data type
print(a.size) # no of elements
print(a.itemsize) # no of bytes for each items
print(a.ndim) # no of dimensions
print(a.nbytes)# total array size in bytes a.size * a.itemsize
print(a)

(4,)
int8
4
1
1
4
[1 2 3 7]


In [17]:
a = np.array([1,2,3,7,(2**32)+1])
print(a.dtype)

int64


In [18]:
a = np.array([1,2,3,7,'python'])
print(a.dtype)

<U11


In [19]:
a = np.array([1,2,3,7,None])
print(a.dtype)
type(a[0])

object


int

In [20]:
a = np.array([1,2,3,7,np.nan])
print(a.dtype)

float64


Initializing Arrays
- zeros
- ones
- full
- eye
- diag

In [21]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

In [22]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.ones((2,3),bool)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [26]:
np.ones((2,3),bool)

array([[ True,  True,  True],
       [ True,  True,  True]])

Creating arrays in a range
- arange
- linspace

In [27]:
import numpy as np
np.arange(5)

array([0, 1, 2, 3, 4])

In [28]:
np.arange(10,100,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [29]:
np.arange(5,10,0.5)

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [30]:
np.linspace(5,10,10)

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [31]:
np.linspace(5,10.5,10)

array([ 5.        ,  5.61111111,  6.22222222,  6.83333333,  7.44444444,
        8.05555556,  8.66666667,  9.27777778,  9.88888889, 10.5       ])

# mathameical operator

In [32]:
import numpy as np
np.diag(2,3,4)

TypeError: diag() takes from 1 to 2 positional arguments but 3 were given

In [33]:
a = np.arange(5)
b = np.ones(5)
print(a)
print(b)

[0 1 2 3 4]
[1. 1. 1. 1. 1.]


In [34]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a//b)


[1. 2. 3. 4. 5.]
[-1.  0.  1.  2.  3.]
[0. 1. 2. 3. 4.]
[0. 1. 2. 3. 4.]
[0. 0. 0. 0. 0.]
[0. 1. 2. 3. 4.]


In [35]:
print(a*2)
print(a**2)
print(a-2)
print(a+2)
print(a/2)

[0 2 4 6 8]
[ 0  1  4  9 16]
[-2 -1  0  1  2]
[2 3 4 5 6]
[0.  0.5 1.  1.5 2. ]


# Random

In [37]:
np.random.randint(100)

66

In [39]:
np.random.randint(100,size=5)

array([19, 94, 93, 39,  1])

In [43]:
np.random.randint(100,size=(5,3))

array([[84, 62, 63],
       [56, 66, 82],
       [20, 13, 52],
       [60, 75, 85],
       [ 3, 62, 22]])

In [46]:
np.random.randint(100,200,size=(5,4))

array([[182, 120, 142, 147],
       [118, 157, 119, 169],
       [149, 113, 153, 162],
       [198, 126, 179, 102],
       [175, 125, 170, 164]])

In [50]:
print(help(np.random.randint))
# print(help(np.random.random))

Help on built-in function randint:

randint(...) method of mtrand.RandomState instance
    randint(low, high=None, size=None, dtype='l')
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    Parameters
    ----------
    low : int
        Lowest (signed) integer to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above for behavior if ``high=None``).
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, i

In [54]:
np.random.rand(1,4)

array([[0.31755129, 0.00423434, 0.01877652, 0.16302223]])

In [58]:
dir(random)

['Lock',
 'RandomState',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'absolute_import',
 'beta',
 'binomial',
 'bytes',
 'chisquare',
 'choice',
 'dirichlet',
 'division',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'np',
 'operator',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'print_function',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponential',
 'standard_gamma',
 'standard_normal',
 'standard_t',
 'test',
 'triangular',
 'uniform',
 'vonmises',
 'wald',
 'warnings',
 'weibull',
 'zipf']

In [59]:
help(np.random.shuffle)

Help on built-in function shuffle:

shuffle(...) method of mtrand.RandomState instance
    shuffle(x)
    
    Modify a sequence in-place by shuffling its contents.
    
    This function only shuffles the array along the first axis of a
    multi-dimensional array. The order of sub-arrays is changed but
    their contents remains the same.
    
    Parameters
    ----------
    x : array_like
        The array or list to be shuffled.
    
    Returns
    -------
    None
    
    Examples
    --------
    >>> arr = np.arange(10)
    >>> np.random.shuffle(arr)
    >>> arr
    [1 7 5 2 9 4 3 6 0 8]
    
    Multi-dimensional arrays are only shuffled along the first axis:
    
    >>> arr = np.arange(9).reshape((3, 3))
    >>> np.random.shuffle(arr)
    >>> arr
    array([[3, 4, 5],
           [6, 7, 8],
           [0, 1, 2]])



In [70]:
r = np.arange(10,20)
np.random.shuffle(r)
print(r)

[11 15 13 19 17 14 16 10 12 18]


# Array Manupulation
- np.array.reshape
- np.resize
- np.array.resize
- np.expand_dims
- np.flaten

In [74]:
a = np.arange(20)
a.reshape(5,4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [76]:
a.reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [77]:
a.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [79]:
a.reshape(20,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [134]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [93]:
a.resize(10,2)

In [91]:
z = np.arange(20)
y=z.resize(10,2)
print(y)


None


In [95]:
np.expand_dims(a,1)

array([[[ 0,  1]],

       [[ 2,  3]],

       [[ 4,  5]],

       [[ 6,  7]],

       [[ 8,  9]],

       [[10, 11]],

       [[12, 13]],

       [[14, 15]],

       [[16, 17]],

       [[18, 19]]])

In [96]:
np.expand_dims(a,0)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [100]:
a2 = np.arange(10).reshape(2,5)
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [108]:
np.expand_dims(a2,1)

array([[[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

In [109]:
np.expand_dims(a2,1).shape

(2, 1, 5)

In [106]:
np.expand_dims(a2,0)

array([[[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]])

In [112]:
a2.flatten()     # it will converted into 1D array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

iteration over 1d,2d and 3d 

In [115]:
print(a)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [118]:
for i in a:
    print(i)
    break

[0 1]


In [133]:
print(a2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [117]:
for i in a2:
    print(i)
    break

[0 1 2 3 4]


In [119]:

for i in np.arange(10).reshape(2,5):
    print(i)
    break

[0 1 2 3 4]


In [135]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [136]:
a.reshape(1,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [137]:
print(a[0])
print(a[-1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [138]:
print(a[2:10])

[]


In [139]:
a[a % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [143]:
a2[1:3]

array([[5, 6, 7, 8, 9]])

In [144]:
a2[[True,False]]

array([[0, 1, 2, 3, 4]])

In [146]:
a2.shape

(2, 5)

In [148]:
a.shape

(1, 20)

In [150]:
a2[1,2]

7

In [151]:
print(a2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [155]:
a2[0:3,1:3]

array([[1, 2],
       [6, 7]])

In [158]:
a2[[0,1],[0,1]]

array([0, 6])

# Time comparition

In [1]:
import time
import numpy as np
start = time.time()
l = [x*x for x in range(1000000)]
end = time.time()
print("time taken for list: ",end-start)

start = time.time()
l = np.arange(1000000)
end = time.time()
print("time taken for array: ",end-start)

time taken for list:  0.1311042308807373
time taken for array:  0.01801156997680664


# Trigonometric functionas

In [2]:
np.sin(3.14/2)

0.9999996829318346

In [3]:
np.arcsin(1)

1.5707963267948966

In [6]:
np.rad2deg(1.5707963267948966)

90.0

In [7]:
np.deg2rad(90)

1.5707963267948966

In [10]:
import math
math.sin(2)

0.9092974268256817

# Log and exp functions

In [15]:
print(np.log(2))
print(np.log(1))
print(np.log(np.exp(2)))


0.6931471805599453
0.0
2.0


In [16]:
print(np.log(0))

-inf


C:\Users\USER\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


In [17]:
print(np.log2(2))
print(np.log2(32))

1.0
5.0


In [20]:
print(np.log1p(2))  # np.log1p(x) = np.log(1+x)

1.0986122886681098


In [21]:
print(np.log(2+1))

1.0986122886681098


In [22]:
print(np.exp(1))

2.718281828459045


In [24]:
print(np.exp2(2))

4.0


In [26]:
print(np.expm1(5))
print(np.exp(5)-1)          # print(np.expm1(x)) = print(np.expm1())

147.4131591025766
147.4131591025766


In [35]:
a = np.random.randint(100,size = 5)
a

array([77,  1,  5, 57, 92])

In [36]:
print(a.sum())
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))

232
232
46.4
57.0
37.15696435394043
1380.6399999999999


In [39]:
np.sort(a)

array([ 1,  5, 57, 77, 92])

In [41]:
print(np.quantile(a,0.25))
print(np.quantile(a,0.5))
print(np.quantile(a,0.75))

5.0
57.0
77.0


# Broadcasting

In [44]:
a = np.arange(5)
b = np.arange(4)
a+b

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [50]:
a = np.arange(10).reshape(5,2)
b = np.arange(2)
a+b

array([[ 0,  2],
       [ 2,  4],
       [ 4,  6],
       [ 6,  8],
       [ 8, 10]])

In [52]:
a,b

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]), array([0, 1]))

In [63]:
a = np.arange(15).reshape(5,3)
b = np.arange(5).reshape(5,1)
a*b

array([[ 0,  0,  0],
       [ 3,  4,  5],
       [12, 14, 16],
       [27, 30, 33],
       [48, 52, 56]])

In [72]:
a = np.arange(15).reshape(5,3)
print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

105
[30 35 40]
[ 3 12 21 30 39]


In [81]:
np.random.seed(5)
a = np.random.randint(50,size=10)
b = np.random.randint(50,size=10)
print(a)
print(b)

[35 14 47 38 16  9  8 36 39 27]
[48 30 16  7 12 15 49 39 16 27]


In [82]:
help(np.random.seed)

Help on built-in function seed:

seed(...) method of mtrand.RandomState instance
    seed(seed=None)
    
    Seed the generator.
    
    This method is called when `RandomState` is initialized. It can be
    called again to re-seed the generator. For details, see `RandomState`.
    
    Parameters
    ----------
    seed : int or 1-d array_like, optional
        Seed for `RandomState`.
        Must be convertible to 32 bit unsigned integers.
    
    See Also
    --------
    RandomState



In [83]:
def maxnumber(n1,n2):
    if n1>n2:
        return n1
    else:
        return n2
maxnumber(5,44)

44

In [84]:
maxnumber_vec = np.vectorize(maxnumber)
maxnumber_vec(a,b)

array([48, 30, 47, 38, 16, 15, 49, 39, 39, 27])

# stacking

In [85]:
a = np.arange(6)
b = np.arange(6)
np.hstack([a,b])

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])

In [86]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [89]:
a = np.arange(6).reshape(2,3)
b = np.arange(2).reshape(2,1)
np.hstack([a,b])

array([[0, 1, 2, 0],
       [3, 4, 5, 1]])

# Linear Algebra

In [90]:
np.linalg.det(np.eye(2))

1.0

In [91]:
np.linalg.det(np.array([[1,2],[5,7]]))

-2.999999999999999

In [92]:
np.linalg.inv(np.array([[1,2],[5,7]]))

array([[-2.33333333,  0.66666667],
       [ 1.66666667, -0.33333333]])

In [94]:
np.linalg.matrix_rank(np.array([[2,3],[5,7]]))

2

- np.dot
- np.matmul

In [96]:
help(np.dot)

Help on built-in function dot in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
      and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Second argument.
 