#### Time comparision

In [5]:
import time
import numpy as np
start = time.time()
l= [x*x for x in range(100000)]
end = time.time()
print('time with lists: ',end-start)
start = time.time()
a = np.arange(100000)
a = a*a
end = time.time()
print('time with np arrays: ',end-start)


time with lists:  0.011196374893188477
time with np arrays:  0.0010609626770019531


###### Trigonometric functions

In [8]:
a = np.random.randint(100,size =23)
np.sin(a)

array([-0.55878905,  0.01770193,  0.55142668, -0.44411267, -0.64353813,
        0.86006941, -0.92345845,  0.        ,  0.56610764, -0.76825466,
       -0.00885131, -0.521551  , -0.8462204 , -0.13235175, -0.24525199,
        0.89399666, -0.98803162, -0.99177885, -0.67677196, -0.85551998,
        0.85090352,  0.43616476, -0.95375265])

In [10]:
np.sin(3.14/2)

0.9999996829318346

In [11]:
np.arcsin(1)

1.5707963267948966

In [12]:
np.rad2deg(1.5707963267948966)

90.0

In [13]:
np.deg2rad(90)

1.5707963267948966

In [14]:
import math
math.sin(a)

TypeError: only size-1 arrays can be converted to Python scalars

In [15]:
math.sin([2,3])

TypeError: must be real number, not list

#### Log and Exponential functions

In [18]:
print(np.log(2))
print(np.log(1))
print(np.log(np.exp(1)))

0.6931471805599453
0.0
1.0


In [19]:
print(np.log2(2))
print(np.log2(32))

1.0
5.0


In [20]:
np.log(0)

C:\Users\Krish\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [21]:
np.log1p(2)
# np.log1p(x) = np.log(1+x)

1.0986122886681098

In [22]:
np.log(2+1)

1.0986122886681098

In [25]:
print(np.exp(1))
print(np.exp2(2))

2.718281828459045
4.0


In [29]:
print(np.expm1(5))
print(np.exp(5)-1)
# np.expm1(x) = np.exp(x)-1

147.4131591025766
147.4131591025766


##### Statistics

In [43]:
a = np.random.randint(100,size=5)
a

array([24, 84, 10, 33, 43])

In [40]:
print(a.sum())
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))

190
190
38.0
30.0
22.969545054266966


In [44]:
np.sort(a)

array([10, 24, 33, 43, 84])

In [45]:
print(np.quantile(a,0.25))
print(np.quantile(a,0.5))
print(np.quantile(a,0.75))

24.0
33.0
43.0


##### Broadcasting

In [46]:
a = np.arange(5)
b = np.arange(4)
a+b

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [47]:
a = np.arange(10).reshape(5,2)
b = np.arange(2)
a+b

array([[ 0,  2],
       [ 2,  4],
       [ 4,  6],
       [ 6,  8],
       [ 8, 10]])

In [49]:
a = np.arange(10).reshape(5,2)
b = np.arange(5)
a+b

ValueError: operands could not be broadcast together with shapes (5,2) (5,) 

In [52]:
a = np.arange(15).reshape(5,3,1)
b = np.arange(5)
a+b

array([[[ 0,  1,  2,  3,  4],
        [ 1,  2,  3,  4,  5],
        [ 2,  3,  4,  5,  6]],

       [[ 3,  4,  5,  6,  7],
        [ 4,  5,  6,  7,  8],
        [ 5,  6,  7,  8,  9]],

       [[ 6,  7,  8,  9, 10],
        [ 7,  8,  9, 10, 11],
        [ 8,  9, 10, 11, 12]],

       [[ 9, 10, 11, 12, 13],
        [10, 11, 12, 13, 14],
        [11, 12, 13, 14, 15]],

       [[12, 13, 14, 15, 16],
        [13, 14, 15, 16, 17],
        [14, 15, 16, 17, 18]]])

In [55]:
a = np.arange(15).reshape(5,3)
print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

105
[30 35 40]
[ 3 12 21 30 39]


 ##### Vectorize

In [62]:
np.random.seed(5)
a = np.random.randint(50,size=10)
b = np.random.randint(50,size=10)
print(a)
print(b)

[35 14 47 38 16  9  8 36 39 27]
[48 30 16  7 12 15 49 39 16 27]


In [60]:
help(np.random.seed)

Help on built-in function seed:

seed(...) method of mtrand.RandomState instance
    seed(seed=None)
    
    Seed the generator.
    
    This method is called when `RandomState` is initialized. It can be
    called again to re-seed the generator. For details, see `RandomState`.
    
    Parameters
    ----------
    seed : int or 1-d array_like, optional
        Seed for `RandomState`.
        Must be convertible to 32 bit unsigned integers.
    
    See Also
    --------
    RandomState



In [64]:
def maxnumber(n1,n2):
    if n1>n2:
        return n1
    else:
        return n2
maxnumber(5,44)

44

In [65]:
maxnumber_vec = np.vectorize(maxnumber)
maxnumber_vec(a,b)

array([48, 30, 47, 38, 16, 15, 49, 39, 39, 27])

##### stacking

In [67]:
a = np.arange(6)
b = np.arange(6)
np.hstack([a,b])

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])

In [68]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [69]:
a = np.arange(6).reshape(2,3)
b = np.arange(6).reshape(2,3)
np.hstack([a,b])

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [82]:
a = np.arange(6).reshape(2,3)
b = np.arange(3)
np.vstack([a,b])

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2]])

Linear Algebra

In [83]:
np.linalg.det(np.eye(2))

1.0

In [84]:
np.linalg.det(np.array([[1,2],[5,7]]))

-2.999999999999999

In [87]:
np.linalg.inv(np.array([[1,2],[5,7]]))

array([[-2.33333333,  0.66666667],
       [ 1.66666667, -0.33333333]])

In [89]:
np.linalg.matrix_rank(np.array([[1,2],[5,7]]))

2

- np.dot
- np.matmul